-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     user_id INT,
--     first_name VARCHAR(50),
--     last_name VARCHAR(50),
--     email VARCHAR(100),
--     password VARCHAR(50),
--     role VARCHAR(50)
-- );
